version: '3.8' # Or a suitable version for your setup

services:
  db:
    image: postgres:14-alpine # Adjust version as needed
    restart: always
    environment:
      POSTGRES_USER: micronaut
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: db
    ports:
      - '5432:5432'
